// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Figurine.Tests")>]
[<assembly: AssemblyProductAttribute("Figurine")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-12-09T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","da0f71b4c8c70f580d92e55073a56fbf70d61317")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Figurine.Tests"
    let [<Literal>] AssemblyProduct = "Figurine"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-12-09T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "da0f71b4c8c70f580d92e55073a56fbf70d61317"
